gsb_account:
    resource: "@GSBAccountBundle/Resources/config/routing.yml"
    prefix:   /

gsb_app:
    resource: "@GSBAppBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

login:
    pattern:   /login
    defaults:  { _controller: GSBAccountBundle:Security:login }

login_check:
    pattern:   /login_check

logout:
    pattern:   /logout