<?php

namespace GSB\AppBundle\Repository;

/**
 * LigneFraisForfaitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LigneFraisForfaitRepository extends \Doctrine\ORM\EntityRepository
{
}
