<?php

namespace GSB\AccountBundle\Repository;

/**
 * comptableRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComptableRepository extends \Doctrine\ORM\EntityRepository
{
}
