<?php

namespace GSB\AccountBundle\Repository;

/**
 * visiteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VisiteurRepository extends \Doctrine\ORM\EntityRepository
{
}
